### ISSUE TITLE
add support for arch Linux

### ISSUE THREAD

**Issue by theoneandonly-vector** [r00t-3xp10it/venom#10]
there are multiple errors on arch linux.
please add support :)

**Comment by ChaitanyaHaritash** [comment]
only distro it supports for now is 
- Debian based
- Ubuntu based

sorry, but we haven't made it Arch supportive yet :) 
thanks for reporting tho..

**Comment by theoneandonly-vector** [comment]
It was a feature request :)

**Comment by r00t-3xp10it** [comment]
well ..
maybee with your help i can make this work on arch ..
i dont have any team menber with arch, so i depend on you to report whats wrong ,,,

P.S. iam current working on new version release [v1.0.14] ...
