### ISSUE TITLE
./venom.sh: 7431: xterm: not found and .apk certification

### ISSUE THREAD

**Issue by Stancescu** [r00t-3xp10it/venom#100]
Where can i get the password from this : - Android Apk Certificate Function:
- After Successfully created the .apk file, we need to sign an certificate to it,
- because Android mobile devices are not allowing the installing of apps without
- the signed certificate. This function uses (keytool | jarsigner | zipalign) to
- sign our apk with an SSL certificate (google). We just need to manually input 3
- times a SecretKey (password) when asked further head.
---
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Enter keystore password:

**Comment by r00t-3xp10it** [comment]
`Enter keystore password:` <-- the script its asking YOU to invent a password ...

**Comment by Stancescu** [comment]
Thank you.
