### ISSUE TITLE
Jarsigner command not found

### ISSUE THREAD

**Issue by prince-stark** [r00t-3xp10it/venom#102]
![16214445234718280211934383685297](https://user-images.githubusercontent.com/81898167/118855877-ed232800-b8f3-11eb-974d-a9c2838fc5a6.jpg)

**Comment by prince-stark** [comment]
Jarsigner : command not found

**Comment by r00t-3xp10it** [comment]
Please read this [issue](https://github.com/r00t-3xp10it/venom/issues/48#issuecomment-606774985)
