### ISSUE TITLE
Unable to locate pywin32-220 (x64)

### ISSUE THREAD

**Issue by D4rkX0** [r00t-3xp10it/venom#11]
Hi

during install venom i got this error:

WARNING: Unable to locate pywin32-220 (x64)
Please Download/Install the follow packets
python-2.6.6.amd64.msi
pywin32-220.win-amd64-py2.6.exe

this is my install log:

> __    _ ______  ____   _  _____  ____    __
>    \  \  //|   ___||    \ | |/     \|    \  /  |
>     \  \// |   ___||     \| ||     ||     \/   |
>      \__/  |______||__/\____|\_____/|__/\__/|__|
>    ╔───────────────────────────────────────────╗
>    |    "setup.sh - configuration script"      |
>    |                                           |
>    |   Use this script to configure venom.sh   |
>    | internal settings, like the installation  |
>    | of dependencies, mega-upload domain name  |
>    | path to apache2 webroot, wine install...  |
>    |                                           |
>    ╠───────────────────────────────────────────╝
>    |  OS:Linux DISTRO:Kali(x64) VERSION:1.0.14
>    |_ BROADCAST:eth0 IP_ADDR:192.168.1.206
> 
> 
> 
> [✔] zenity............................[ found ]
> [✔] msfconsole........................[ found ]
> [✔] gcc compiler......................[ found ]
> [✔] mingw64 compiler..................[ found ]
> [✔] pyherion crypter..................[ found ]
> [✔] vbs-obfuscator....................[ found ]
> [✔] apache2 webserver.................[ found ]
> 
> [☆] Building       -> venom mega-upload.conf
> [☆] Building       -> venom domain directory
> [☆] Added          -> DNS record to etter.dns
> [☆] DOMAIN_NAME    -> mega-upload.com
> [☆] ATTACK_VECTOR  -> http://mega-upload.com
> [☆] APACHE_WEBROOT -> /root/venom/aux/public_html/mega-upload.com
> 
> Enabling site mega-upload.
> To activate the new configuration, you need to run:
>   systemctl reload apache2
> 
> [✔] ettercap settings.................[  IPv4 ]
> [✔] wine64............................[ found ]
> [✔] wine folder.......................[ found ]
> [✔] arch sellected....................[ 64bit ]
> [x] WinRAR.exe                    [ not found ]
> 
> fixme:service:scmdatabase_autostart_services Auto-start service L"MountMgr" failed to start: 2
> fixme:heap:RtlSetHeapInformation 0x230000 0 0x22fcd0 4 stub
> fixme:shell:SHAutoComplete stub
> fixme:ieframe:PersistStreamInit_InitNew (0x626f0)
> Could not load wine-gecko. HTML rendering will be disabled.
> err:mshtml:HTMLDocument_Create Failed to init Gecko, returning CLASS_E_CLASSNOTAVAILABLE
> fixme:ole:CoCreateInstanceEx no instance created for interface {00000000-0000-0000-c000-000000000046} of class {25336920-03f9-11cf-8fd0-00aa00686f13}, hres is 0x80040111
> fixme:ieframe:handle_navigation_error Navigate to error page
> fixme:ieframe:bind_to_object BindToObject failed: 800c0010
> fixme:exec:SHELL_execute flags ignored: 0x00000180
> fixme:ieframe:OleInPlaceObject_UIDeactivate (0x626f0)
> fixme:ieframe:OleInPlaceObject_InPlaceDeactivate (0x626f0)
> 
> fixme:heap:RtlSetHeapInformation 0x240000 0 0x23fcd0 4 stub
> 
>     WARNING: Unable to locate WinRAR
>     Please Download WinRAR to: venom-main/bin
>     https://github.com/r00t-3xp10it/venom/blob/master/bin/install_winrar_wine64.exe
> 
> [x] pyinstaller                   [ not found ]
> fixme:nstc:NSTC2_fnSetControlStyle2 mask & style (0x00000004) contains unsupported style(s): 0x00000004
> fixme:shell:IShellBrowser_fnSendControlMsg stub, 0x3b140 (2, 1026, a003, 0, 0x23ede0)
> fixme:shell:IShellBrowser_fnSendControlMsg stub, 0x3b140 (2, 1026, a004, 1, 0x23ede0)
> fixme:shell:IShellBrowser_fnSendControlMsg stub, 0x3b140 (2, 1025, a003, 1, 0x23ede0)
> fixme:shell:IShellBrowser_fnSendControlMsg stub, 0x3b140 (2, 1025, a004, 1, 0x23ede0)
> fixme:shell:IExtractIconW_fnExtract (0x4b3b0) (file=L"C:\\windows\\system32\\shell32.dll" index=-35 (nil) 0x23ebb8 size=00000014) semi-stub
> fixme:shell:IExtractIconW_fnExtract (0x55330) (file=L"C:\\windows\\system32\\shell32.dll" index=-16 (nil) 0x23ebb8 size=00000014) semi-stub
> fixme:shell:IExtractIconW_fnExtract (0x521b0) (file=L"C:\\windows\\system32\\shell32.dll" index=-235 (nil) 0x23ebb8 size=00000014) semi-stub
> fixme:shell:IExtractIconW_fnExtract (0x521e0) (file=L"@C:\\windows\\system32\\shell32.dll" index=-33 (nil) 0x23ebb8 size=00000014) semi-stub
> fixme:shell:IExtractIconW_fnExtract (0x577b0) (file=L"C:\\windows\\system32\\shell32.dll" index=-9 (nil) 0x23ebb8 size=00000014) semi-stub
> fixme:shell:IExtractIconW_fnExtract (0x5be30) (file=L"C:\\windows\\system32\\shell32.dll" index=-4 (nil) 0x23ebb8 size=00000014) semi-stub
> fixme:shell:IExtractIconW_fnExtract (0x5e9b0) (file=L"C:\\windows\\system32\\shell32.dll" index=-4 (nil) 0x23ebb8 size=00000014) semi-stub
> fixme:shell:IExtractIconW_fnExtract (0x5e990) (file=L"C:\\windows\\system32\\shell32.dll" index=-4 (nil) 0x23ebb8 size=00000014) semi-stub
> fixme:shell:IExtractIconW_fnExtract (0x577e0) (file=L"C:\\windows\\system32\\shell32.dll" index=-4 (nil) 0x23ebb8 size=00000014) semi-stub
> fixme:shell:IExtractIconW_fnExtract (0x5e650) (file=L"C:\\windows\\system32\\shell32.dll" index=-4 (nil) 0x23ebb8 size=00000014) semi-stub
> fixme:shell:IExtractIconW_fnExtract (0x5bb60) (file=L"C:\\windows\\system32\\shell32.dll" index=-4 (nil) 0x23ebb8 size=00000014) semi-stub
> fixme:shell:IExtractIconW_fnExtract (0x56f10) (file=L"C:\\windows\\system32\\shell32.dll" index=-4 (nil) 0x23ebb8 size=00000014) semi-stub
> fixme:shell:IExtractIconW_fnExtract (0x5e5e0) (file=L"C:\\windows\\system32\\shell32.dll" index=-4 (nil) 0x23ebb8 size=00000014) semi-stub
>     Copy to: /drive_c/pyinstaller-2.0
> [x] pywin32-220                   [ not found ]
> 
> Install: python-2.6.6.amd64.msi
> 
> fixme:service:scmdatabase_autostart_services Auto-start service L"MountMgr" failed to start: 2
> fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
> err:mscoree:LoadLibraryShim error reading registry key for installroot
> err:mscoree:LoadLibraryShim error reading registry key for installroot
> err:mscoree:LoadLibraryShim error reading registry key for installroot
> err:mscoree:LoadLibraryShim error reading registry key for installroot
> fixme:heap:RtlSetHeapInformation 0x6a0000 0 0x22ec10 4 stub
> fixme:msi:ITERATE_CreateShortcuts poorly handled shortcut format, advertised shortcut
> fixme:msi:ITERATE_CreateShortcuts poorly handled shortcut format, advertised shortcut
> fixme:msi:ITERATE_CreateShortcuts poorly handled shortcut format, advertised shortcut
> 
> Install: pywin32-220.win-amd64-py2.6.exe
> 
> fixme:heap:RtlSetHeapInformation 0x230000 0 0x22fcd0 4 stub
> fixme:msvcrt:__clean_type_info_names_internal (0x1e296510) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x1e296510) stub
> err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
> fixme:msvcrt:__clean_type_info_names_internal (0x1e4e6558) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x1ece54a8) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x1e87e3c0) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x1ebfba00) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x1e8df0f8) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x9417f88) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x1e7c1090) stub
> fixme:msvcrt:__clean_type_info_names_internal (0x1e296510) stub
> 
> 
>     WARNING: Unable to locate pywin32-220 (x64)
>     Please Download/Install the follow packets
>     python-2.6.6.amd64.msi
>     pywin32-220.win-amd64-py2.6.exe
> 
> [✔] Rebuild toolkit settings file.....[  done ]
> sed: -e expression #1, char 0: no previous regular expression
> [✔] All checks completed..............[  done ]
> 
>     Report-Bugs: https://github.com/r00t-3xp10it/venom/issues

**Comment by r00t-3xp10it** [comment]
1 - did you try to install manually the missing dependencies?
(python-2.6.6.amd64.msi & pywin32-220.win-amd64-py2.6.exe)

2 - for testing proposes lets change the sourcecode of 'setup.sh'
to force script to use 32 bytes softwares insted ..
![bug report](http://i.cubeupload.com/yg3tHi.png)

      change the follow values on setup.sh
      1 - Dftt="x64" change it to: Dftt="x86" 
      2 - arch="wine64" change it to: arch="wine"

**Comment by D4rkX0** [comment]
The new Setup work great, thank you.

`[✔] zenity............................[ found ]
[✔] msfconsole........................[ found ]
[✔] gcc compiler......................[ found ]
[✔] mingw64 compiler..................[ found ]
[✔] pyherion crypter..................[ found ]
[✔] vbs-obfuscator....................[ found ]
[✔] apache2 webserver.................[ found ]

[☆] Building       -> venom mega-upload.conf
[☆] Building       -> venom domain directory
[☆] Added          -> DNS record to etter.dns
[☆] DOMAIN_NAME    -> mega-upload.com
[☆] ATTACK_VECTOR  -> http://mega-upload.com
[☆] APACHE_WEBROOT -> /root/venom/aux/public_html/mega-upload.com

Site mega-upload already enabled

[✔] ettercap settings.................[  IPv4 ]
[✔] wine64............................[ found ]
[✔] wine folder.......................[ found ]
[✔] arch sellected....................[ 64bit ]
[✔] WinRAR.exe........................[ found ]
[x] pyinstaller                   [ not found ]
    Copy to: /root/.wine/drive_c/pyinstaller-2.0
[✔] pywin32-220.......................[ found ]
[✔] Rebuild toolkit settings file.....[  done ]
sed: -e expression #1, char 0: no previous regular expression
[✔] All checks completed..............[  done ]

    Report-Bugs: https://github.com/r00t-3xp10it/venom/issues
`

**Comment by r00t-3xp10it** [comment]
1 - what did you change ?
(Pywin and python its allready installed) ..

2 - check manually if pyinstaller its on wine subfolders .. (drive_c)
If not copy the executable there (it does not required installation).

3 - run again setup.sh to see if everything its done now ..

Have fun ..

Em 31/08/2017 17:34, "D4rkX0" <notifications@github.com> escreveu:

**Comment by sirhcthereal** [comment]
Hey. I got the same issue like the user above, but my problem is that "wine64 pywin32-220.win-amd64-py2.6.exe)" does not work, not with and not without the ")" at end. Can I download it manually and where do I have to put it?
And also: I have the this error at the end:
"
[✔] Rebuild toolkit settings file.....[  done ]
sed: can't read settings: No such file or directory
sed: can't read settings: No such file or directory
sed: can't read settings: No such file or directory
sed: can't read settings: No such file or directory
sed: can't read settings: No such file or directory
sed: can't read settings: No such file or directory
sed: can't read settings: No such file or directory
sed: can't read settings: No such file or directory
[✔] All checks completed..............[  done ]
"
Thanks for your help.

**Comment by r00t-3xp10it** [comment]
Hello iam on vacations ( no pc available ) ..

1- did you try to install the dependencies manually ?

2- settings file its venom config file ..it can be found under:
https://github.com/r00t-3xp10it/venom/blob/master/settings



A Sáb, 25/08/2018, 18:01, sirhcthereal <notifications@github.com> escreveu:
