### ISSUE TITLE
metasploit LHOST bad configuration ..

### ISSUE THREAD

**Issue by Tiger120utt** [r00t-3xp10it/venom#114]
when i'm on my android and search this addres but is not working 
![1628421229292-172676206](https://user-images.githubusercontent.com/88607328/128630129-5890d071-6175-499d-9309-06786ceefba7.jpg)
Look this

**Comment by r00t-3xp10it** [comment]
`You are binding to a loopback address by setting LHOST to 127.0.0.1.`
LHOST = Attacker machine IP address ...

**Comment by Tiger120utt** [comment]
> **ERROR:** `You are binding to a loopback address by setting LHOST to 127.0.0.1.`
> LHOST = Attacker machine IP address ..

But 127.0.0.1 is my address and I am attacker 
![Uploading 1628663551210-172676206.jpg…]()

**Comment by Tiger120utt** [comment]
> **ERROR:** `You are binding to a loopback address by setting LHOST to 127.0.0.1.`
> LHOST = Attacker machine IP address ...
 
Hey thanks I will understand wt u say ☺️

**Comment by Tiger120utt** [comment]
This is my mistake I will using a Worng ip
