### ISSUE TITLE
cannot find gcc.exe

### ISSUE THREAD

**Issue by emeykey** [r00t-3xp10it/venom#12]
wine: cannot find L"C:\\windows\\system32\\gcc.exe"
any suggestions?

**Comment by r00t-3xp10it** [comment]
### I need a little more information ...

* what system are you using ?
* what arch your system uses (32 or 64 bits)
* what venom option (number) are you trying to run?

<br />

### Hint:

    the option [24] of venom uses 'mingw-gcc' installed inside 'wine' (32 bits). 
    it looks like wine32 is missing, you should install it. multiarch needs to be enabled first. 
    as root, please execute "dpkg --add-architecture i386 && apt-get update && apt-get install wine32"

**Comment by emeykey** [comment]
Thank you for reply, honestly it was only my own stupidity. I somehow managed to uninstall MinGW compiler and gcc etc with it, dunno how, but did. Everything works great, thanks once again. :)
