### ISSUE TITLE
Script execution aborted ..

### ISSUE THREAD

**Issue by sharkersharif** [r00t-3xp10it/venom#13]
__    _ ______  ____   _  _____  ____    __
   \  \  //|   ___||    \ | |/     \|    \  /  |
    \  \// |   ___||     \| ||     ||     \/   |
     \__/  |______||__/\____|\_____/|__/\__/|__|
   ╔───────────────────────────────────────────╗
   |    "setup.sh - configuration script"      |
   |                                           |
   |   Use this script to configure venom.sh   |
   | internal settings, like the installation  |
   | of dependencies, mega-upload domain name  |
   | path to apache2 webroot, wine install...  |
   |                                           |
   ╠───────────────────────────────────────────╝
   |  OS:Linux DISTRO:(x64) VERSION:1.0.14
   |_ BROADCAST: IP_ADDR:

[x] Script execution aborted ..
    Report-Bugs: https://github.com/r00t-3xp10it/venom/issues

root@j5xnlte:/data/data/com.termux/files/home/venom/aux #

**Comment by sharkersharif** [comment]
I tried to use venom in Termux on android

**Comment by r00t-3xp10it** [comment]
well i didnt write the tool to be compatible with android ..

**Comment by sharkersharif** [comment]
Will you please help android users to get such a useful tool? We will be
obliged if u let us use this.
