### ISSUE TITLE
Error Connecting to Posgresql Database (metasploit)

### ISSUE THREAD

**Issue by r00t-3xp10it** [r00t-3xp10it/venom#2]
# bug description
    New upgrade in postgresql-9.6 have changed the default access port from 5432 to 5433
    and stoped the support of postgresql in localhost (127.0.0.1), this article explains
    how to fix the postgresql database connection issue of metasploit in kali linux distros.

> Metasploit database error connecting to postgresql service/port(5432)
![postgresql error](http://4.1m.yt/8F7oZWe.png)
![postgresql error](http://3.1m.yt/jLtH6F8.png)

<br /><br /><br />
# msfdb connection Fix (manual)

> 1º - Locate postgresql configuration files (9.5 and 9.6)

    locate postgresql.conf

> 2º - Edit configuration files

    nano /etc/postgresql/9.6/main/postgresql.conf

> 3º - Search for '''port''' inside the postgresql.conf 
> And change the next values: [ listen_addresses | port | unix_socket_permissions ] 
![postgresql error](http://4.1m.yt/srf84A8.png)

> 4º - Start postgresql service

    service postgresql start
    service postgresql status
![postgresql error](http://2.1m.yt/aSahtN.png)

> 5º - Check if port 5432(postgresql) its listenning on 'localhost'

    ss -ant | grep 5432
![postgresql error](http://3.1m.yt/7yxj3tI.png)

> 6º - Delele old database (database.yml) configurations
> "This next step will delete all hosts/creds/etc current stored into current db"

    msfdb delete

> 7º - Creating new database.yml
> "No need to enter any value (username:password), all proccess its automatized"

    msfdb init
![postgresql error](http://1.1m.yt/dSEHssj.png)

> 8º - Start metasploit console

    msfconsole

> 9º - Check connection to database

    db_status
![postgresql error](http://1.1m.yt/SWTcfBw.png)

<br /><br />

_EOF

**Comment by spiritedwolf** [comment]
cool :D hope it will help us in future.

**Comment by r00t-3xp10it** [comment]
<br />

## **postgresql metasploit database connection fix script:**
WARNING: This script was writen for linux kali 2.0 rolling distros ..`
![postgresql error](https://dl.dropboxusercontent.com/u/21426454/github/msfdb_fix.jpg)
**Download:** [postgresql metasploit database connection fix](https://github.com/r00t-3xp10it/venom/blob/master/aux/msfdb_fix.sh) **(Kali 2.0 rolling)**

<br />

_EOF

**Comment by spiritedwolf** [comment]
Great now we can use it :D

**Comment by gearcapitan** [comment]
Because I do not see anything
![kali linux-2017-04-08-20-07-17](https://cloud.githubusercontent.com/assets/13740942/24833700/0b3bc3ea-1c97-11e7-839a-a55a1ddc2fa0.png)

**Comment by gearcapitan** [comment]
Finish by completely installing the postgre,    :P

**Comment by gearcapitan** [comment]
no te llega a suceder que cuando reinicias, el problema regresa?, como que el problema viene y se va, viene y se va

**Comment by r00t-3xp10it** [comment]
yap ..
I've have came up with a soluction for this strange metasploit bug ..
Save next document with the bash extension (msfix.sh)

    #!/bin/sh
    service postgresql start
        echo "[☆] Checking msfdb connection status .."
        ih=`msfconsole -q -x 'db_status; exit -y' | awk {'print $3'}`
          if [ "$ih" != "connected" ]; then
            echo "[x] postgresql selected, no connection .."
            echo "[☆] Please wait, rebuilding msf database .."
            #
            # Rebuild msf database (database.yml)
            # 
            msfdb reinit | zenity --progress --pulsate --title "☠ PLEASE WAIT ☠" --text="Rebuild metasploit database" --percentage=0 --auto-close --width 300 > /dev/null 2>&1
            echo "[✔] postgresql connected to msf .."
            sleep 2
          else
            echo "[✔] postgresql connected to msf .."
            sleep 2
          fi

<br />

**NOTE:** This code has allready implemented in all my projects ..

**Comment by gearcapitan** [comment]
hola amigo, sonara estupido pero ya desde hace mucho tiempo atras, encontre mi error particular con el servicio de postgresql , resulta que habia editado el archivo /etc/systemd/system.conf  y en los paremetros #DefaultTimeoutStartSec=90s
#DefaultTimeoutStopSec=90s
les habia puesto 3 segundos, y ya, eso era todo lo que me causaba problemas
