### ISSUE TITLE
help

### ISSUE THREAD

**Issue by General-HeRoo** [r00t-3xp10it/venom#21]
[☠] editing/backup files...
[☠] chars.raw -> found!
[☠] Building template -> template.c!
[☠] Compiling template.c -> backdoor.exe!
./venom.sh: 4871: ./venom.sh: i586-mingw32msvc-gcc: not found
strip: '/root/Desktop/venom-master/output/backdoor.exe': No such file

**Comment by r00t-3xp10it** [comment]
### There are two ways we can fix that ..

<br />

- 1º - How to install mingw: [fix kali 2.0 (rolling) mingw32 repository install](https://github.com/r00t-3xp10it/venom/issues/1)

<br />

- 2º - edit venom.sh file and change the next values to suite your needs
![venom.sh file](http://i.cubeupload.com/85LV4W.png)
