### ISSUE TITLE
unable to locate pywin,python,pyinstaller,winrar

### ISSUE THREAD

**Issue by usama7628674** [r00t-3xp10it/venom#22]
When I run setup.sh script I get this.

> [✔] zenity............................[ found ]
[✔] msfconsole........................[ found ]
[✔] gcc compiler......................[ found ]
[✔] mingw64 compiler..................[ found ]
[✔] pyherion crypter..................[ found ]
[✔] vbs-obfuscator....................[ found ]
[✔] apache2 webserver.................[ found ]
[!] Venom Domain name Configuration...[ skipp ]
[✔] ettercap settings.................[  IPv4 ]
[✔] wine64............................[ found ]
[✔] wine folder.......................[ found ]
[✔] arch sellected....................[ 64bit ]
[x] WinRAR.exe                    [ not found ]

0009:fixme:heap:RtlSetHeapInformation 0x250000 0 0x23fd30 4 stub
0009:fixme:shell:SHAutoComplete stub
0009:fixme:ieframe:PersistStreamInit_InitNew (0x669e0)
Could not load wine-gecko. HTML rendering will be disabled.
0009:err:mshtml:create_document_object Failed to init Gecko, returning CLASS_E_CLASSNOTAVAILABLE
0009:fixme:ole:CoCreateInstanceEx no instance created for interface {00000000-0000-0000-c000-000000000046} of class {25336920-03f9-11cf-8fd0-00aa00686f13}, hres is 0x80040111
0009:fixme:ieframe:handle_navigation_error Navigate to error page
0009:fixme:ieframe:bind_to_object BindToObject failed: 800c0010
0009:fixme:shell:BrsFolder_OnCreate flags BIF_NEWDIALOGSTYLE partially implemented
0009:fixme:ntdll:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
0009:fixme:exec:SHELL_execute flags ignored: 0x00000180
0009:fixme:ieframe:OleInPlaceObject_UIDeactivate (0x669e0)
0009:fixme:ieframe:OleInPlaceObject_InPlaceDeactivate (0x669e0)

003e:fixme:heap:RtlSetHeapInformation 0x240000 0 0x23fd30 4 stub

    WARNING: Unable to locate WinRAR
    Please Download WinRAR to: venom-main/bin
    https://github.com/r00t-3xp10it/venom/blob/master/bin/install_winrar_wine64.exe

[x] pyinstaller                   [ not found ]
    Copy to: /drive_c/pyinstaller-2.0
[x] pywin32-220                   [ not found ]

Install: python-2.6.6.amd64.msi

002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0054:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0054:err:mscoree:LoadLibraryShim error reading registry key for installroot
0054:err:mscoree:LoadLibraryShim error reading registry key for installroot
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0054:err:mscoree:LoadLibraryShim error reading registry key for installroot
0054:err:mscoree:LoadLibraryShim error reading registry key for installroot
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0056:fixme:nstc:NSTC2_fnSetControlStyle2 mask & style (0x00000004) contains unsupported style(s): 0x00000004
0056:fixme:shell:IShellBrowser_fnSendControlMsg stub, 0x3d5a0 (2, 1026, a003, 0, 0x23ee30)
0056:fixme:shell:IShellBrowser_fnSendControlMsg stub, 0x3d5a0 (2, 1026, a004, 1, 0x23ee30)
0056:fixme:shell:IShellBrowser_fnSendControlMsg stub, 0x3d5a0 (2, 1025, a003, 1, 0x23ee30)
0056:fixme:shell:IShellBrowser_fnSendControlMsg stub, 0x3d5a0 (2, 1025, a004, 1, 0x23ee30)
0054:err:msi:ITERATE_Actions Execution halted, action L"MaintenanceTypeDlg" returned 1602

Install: pywin32-220.win-amd64-py2.6.exe

wine: Unhandled page fault on read access to 0x7f1128525320 at address 0x7f112aa1af97 (thread 002c), starting debugger...
0009:fixme:heap:RtlSetHeapInformation 0x250000 0 0x23fd30 4 stub

002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!

    WARNING: Unable to locate pywin32-220 (x64)
    Please Download/Install the follow packets
    python-2.6.6.amd64.msi
    pywin32-220.win-amd64-py2.6.exe

wine: Unhandled page fault on read access to 0x7fada7be4320 at address 0x7fadb6182f97 (thread 002c), starting debugger...
002c:err:seh:start_debugger Couldn't start debugger ("winedbg --auto 32 88") (1115)
Read the Wine Developers Guide on how to set up winedbg or another debugger
[✔] Rebuild toolkit settings file.....[  done ]
sed: -e expression #1, char 0: no previous regular expression
[✔] All checks completed..............[  done ]

    Report-Bugs: https://github.com/r00t-3xp10it/venom/issues

Even though they are installed in wine/drive_c directory.I have also tried on live kali and parrot os but still no luck.
Version 1.0.14 works fine though.

**Comment by usama7628674** [comment]
@r00t-3xp10it Thanks for your reply.No,you don't get it.Mingw isn't a problem.The problem is winrar,pyinstaller,pywin,python.They all are installed in .wine/drive_c directory but setup couldn't find them but I still ran venom script and selected option 2 which is windows payloads then option 16 then it says at the end **pyinstaller is not found**.Even though it exists and installed.I even tried on live kali and parrot os but nothing happened.

**Comment by r00t-3xp10it** [comment]
venom reads the config of **settings** file

![](http://i.cubeupload.com/R9QEYf.png)
![](http://i.cubeupload.com/0y3mzO.png)

<br />

agent 16 pyinstaller funtion
![](http://i.cubeupload.com/OsJPUN.png)
![](http://i.cubeupload.com/tdWgzD.png)

**Comment by usama7628674** [comment]
@r00t-3xp10it You're using kali 32 bit.

**Comment by usama7628674** [comment]
@r00t-3xp10it This time on live kali 32-bit (2018.1).Output of setup.sh is following.

OS:Linux DISTRO:Kali(x86) VERSION:1.0.15
[✔] zenity............................[ found ]
[✔] msfconsole........................[ found ]
[✔] gcc compiler......................[ found ]
[✔] mingw32 compiler..................[ found ]
[✔] pyherion crypter..................[ found ]
[✔] vbs-obfuscator....................[ found ]
[✔] apache2 webserver.................[ found ]
[!] Venom Domain name Configuration...[ skipp ]
[✔] ettercap settings.................[  IPv4 ]
[✔] wine..............................[ found ]
[✔] wine folder.......................[ found ]
[✔] arch sellected....................[ 32bit ]
[x] WinRAR.exe                    [ not found ]

Could not load wine-gecko. HTML rendering will be disabled.
0009:err:mshtml:create_document_object Failed to init Gecko, returning CLASS_E_CLASSNOTAVAILABLE


    WARNING: Unable to locate WinRAR
    Please Download WinRAR to: venom-main/bin
    https://github.com/r00t-3xp10it/venom/blob/master/bin/install_winrar_wine32.exe

[x] pyinstaller                   [ not found ]
    Copy to: /drive_c/pyinstaller-2.0
[x] pywin32-220                   [ not found ]

Install: python 2.6.6.msi

0040:err:mscoree:LoadLibraryShim error reading registry key for installroot
0040:err:mscoree:LoadLibraryShim error reading registry key for installroot
0040:err:mscoree:LoadLibraryShim error reading registry key for installroot
0040:err:mscoree:LoadLibraryShim error reading registry key for installroot

Install: pywin32-220.win32-py2.6.exe


wine: Unhandled page fault on read access to 0x7e448c30 at address 0x7ed0acf7 (thread 002f), starting debugger...
002f:err:seh:start_debugger Couldn't start debugger ("winedbg --auto 32 88") (1115)
Read the Wine Developers Guide on how to set up winedbg or another debugger

    WARNING: Unable to locate pywin32-220 (x86)
    Please Download/Install the follow packets
    python-2.6.6.msi
    pywin32-220.win32-py2.6.exe

[✔] Rebuild toolkit settings file.....[  done ]
sed: -e expression #1, char 0: no previous regular expression
[✔] All checks completed..............[  done ]

    Report-Bugs: https://github.com/r00t-3xp10it/venom/issues


![screenshot from 2018-04-10 13-13-43](https://user-images.githubusercontent.com/29252277/38544545-4093e02e-3c97-11e8-969d-c4e1abd8548e.png)



![screenshot from 2018-04-10 13-13-57](https://user-images.githubusercontent.com/29252277/38544567-4786e8a4-3c97-11e8-86d4-4d23bb88f9ef.png)
Setup is not copying pyinstaller so I have to do it manually but still it could not locate winrar,python,pywin,pyinstaller.

**Comment by r00t-3xp10it** [comment]
aaaa something wrong not with my installer but with your wine install ..
because in my side all works perfect, lets install all things manuall ..

<br />

- install winrar under: /root/.wine/drive_c/drive_c/Program Files/WinRAR

      1º - cd venom-main/bin
      2º - wine install_winrar_wine32.exe

<br />

- install pyinstaller under: /root/.wine/drive_c/pyinstaller-2.0

      1º - cd venom-main/obfuscate
      2º - tar -xf pyinstaller.tar.gz
      3º - cd pyinstaller
      4º - mv pyinstaller-2.0 /root/.wine/drive_c/pyinstaller-2.0

<br />

- install python26 + pywin32-220 under: /root/.wine/drive_c/Python26/

      1º - cd venom-main/obfuscate
      2º - tar -xf pyinstaller.tar.gz
      3º - cd pyinstaller
      4º - wine msiexec /i python-2.6.6.msi
      5º - wine pywin32-220.win32-py2.6.exe

<br /><br /><br />

- config settings file under: venom-main/

      remmenber to config the local variable:  WINE_DRIVEC=
      1º - WINE_DRIVEC=/root/.wine/drive_c

![sceenshot](http://i.cubeupload.com/5SCI7p.png)

<br />

**Comment by usama7628674** [comment]
@r00t-3xp10it Ok.I'll give it another shot.

**Comment by usama7628674** [comment]
What should I put in the following box?
![wine box](https://user-images.githubusercontent.com/29252277/38552669-4dd6570a-3cd6-11e8-9c95-2e8de14d01e1.png)

Before running setup my settings file of WINE_DRIVEC

![image](https://user-images.githubusercontent.com/29252277/38552932-21b0f4ae-3cd7-11e8-8687-6316295e22de.png)

after running setup it automatically changes to
![image](https://user-images.githubusercontent.com/29252277/38553209-eeff246c-3cd7-11e8-8f07-61f969c3bd4e.png)

**Comment by usama7628674** [comment]
@r00t-3xp10it So here's the story then setup still not locating but this time I installed everything manually and then executed ./venom.sh and agent 16 is now working fine.There is something wrong in setup but it doesn't matter now cuz problem is solved.

**Comment by r00t-3xp10it** [comment]
if you are using pyinstaller ..then read this :
pyinstaller needs **hidden** imports to work proper ..
[please read this issue](https://github.com/kkar/MSF-Undetector/issues/2)

**Comment by usama7628674** [comment]
@r00t-3xp10it I know about hidden imports but pyinstaller converted .py file to .exe without any error.

**Comment by r00t-3xp10it** [comment]
hey man do you want to help me debug **setup.sh** in 64bits systems ?
after talking to you i have made some changes to setup.sh like:
- 1º - now setup.sh asks to users what arch do we want setup.sh to use to install backend appl
- 2º - setup.sh will also check if the values inputed in sandboxs are correct ..

[we can find the new version of setup.sh here](https://github.com/r00t-3xp10it/venom/blob/master/aux/setup.sh)

**Comment by usama7628674** [comment]
@r00t-3xp10it I'm ready to help just let me know what you want me to test.Oh,and the name of folder is **.wine** under my kali 64bit system.

**Comment by r00t-3xp10it** [comment]
Valueble information (**.wine folder name**)  thanks ..

tell me another thing ...
and **winrar** installed in 64bits its on folder **Program Files** or **ProgramFiles(x86)** ??

what i need you to test is:
- 1º If with the new **setup.sh** we can install all dependencies in a 64bit system ..
- 2º If venom.sh works correct under that configs ..

**Comment by usama7628674** [comment]
@r00t-3xp10it Winrar in Program files and I'll test it tomorrow.Thank you for your reward.
![screenshot from 2018-04-12 19-56-25](https://user-images.githubusercontent.com/29252277/38685547-9ff17180-3e8b-11e8-962a-3652433cec6c.png)

**Comment by usama7628674** [comment]
@r00t-3xp10it The following output is from new setup after recent commits.


OS:Linux DISTRO:Kali(x64) VERSION:1.0.15
[✔] zenity............................[ found ]
[✔] msfconsole........................[ found ]
[✔] gcc compiler......................[ found ]
[✔] mingw64 compiler..................[ found ]
[✔] pyherion crypter..................[ found ]
[✔] vbs-obfuscator....................[ found ]
[✔] apache2 webserver.................[ found ]
[!] Venom Domain name Configuration...[ skipp ]
[✔] ettercap settings.................[  IPv4 ]
[✔] wine64..............................[ found ]
[✔] wine folder.......................[ found ]
[✔] arch sellected....................[ 64bit ]
[✔] WinRAR.exe........................[ found ]
[✔] pyinstaller.......................[ found ]
[✔] pywin32-220.......................[ found ]
[✔] Rebuild toolkit settings file.....[  done ]
sed: -e expression #1, char 0: no previous regular expression
[✔] All checks completed..............[  done ]

    Report-Bugs: https://github.com/r00t-3xp10it/venom/issues


![screenshot from 2018-04-13 08-02-32](https://user-images.githubusercontent.com/29252277/38714764-25c9b9a6-3ef1-11e8-9cc9-535ea5708b86.png)


![screenshot from 2018-04-13 08-04-37](https://user-images.githubusercontent.com/29252277/38714808-5e02fb84-3ef1-11e8-90ea-b55d9f7823cc.png)

**Comment by r00t-3xp10it** [comment]
**sed: -e expression #1, char 0: no previous regular expression** ???
can you check if **settings** file its proper config?

**Comment by usama7628674** [comment]
@r00t-3xp10it 
![screenshot from 2018-04-13 08-14-03](https://user-images.githubusercontent.com/29252277/38715109-bcb9d818-3ef2-11e8-93cd-a491fd4ac52f.png)

**Comment by usama7628674** [comment]
sleep well.Good bye
