### ISSUE TITLE
incomplete setup

### ISSUE THREAD

**Issue by killercoderz4** [r00t-3xp10it/venom#23]
i have setup older version easily. my new rdp is kali 2018. in the aux directory when i run ./setup.sh , i get this error   __    _ ______  ____   _  _____  ____    __
   \  \  //|   ___||    \ | |/     \|    \  /  |
    \  \// |   ___||     \| ||     ||     \/   |
     \__/  |______||__/\____|\_____/|__/\__/|__|
   ╔───────────────────────────────────────────╗
   |    "setup.sh - configuration script"      |
   |                                           |
   |   Use this script to configure venom.sh   |
   | internal settings, like the installation  |
   | of dependencies, mega-upload domain name  |
   | path to apache2 webroot, wine install...  |
   |                                           |
   ╠───────────────────────────────────────────╝
   |  OS:Linux DISTRO:Kali(x64) VERSION:1.0.15
   |_ BROADCAST:eth0 IP_ADDR:xxxxxxxxxxxxxxxx

[x] Script execution aborted ..
    Report-Bugs: https://github.com/r00t-3xp10it/venom/issues

**Comment by usama7628674** [comment]
@killercoderz4 Did you choose yes when a box appear on the screen to execute the script?

**Comment by killercoderz4** [comment]
i figured it because i was accessing my vps via putty ssh. so no gui gets triggered . i need directs access via remote desktop so that the auto script install pops up.on putty it doesnt pop up. anyway i noticed the LFI module doesnt work. when i select option 2 to scan it just does nothing.
