### ISSUE TITLE
[x] Script execution aborted ..

### ISSUE THREAD

**Issue by jbonatelli** [r00t-3xp10it/venom#28]
This is the output when i try to run ./setup.sh. Do you know about the issue ?

**Comment by r00t-3xp10it** [comment]
It seems that your distro its missing the **zenity** packet..
read about it here: https://github.com/r00t-3xp10it/venom/issues/23

**Comment by jbonatelli** [comment]
> It seems that your distro its missing the **zenity** packet..
> read about it here: #23

works ! thank you
