### ISSUE TITLE
Hta payloads not working

### ISSUE THREAD

**Issue by usama7628674** [r00t-3xp10it/venom#30]
Install and ran venom select windows payloads and used agent 9 (HTA-PSH) and upon running .hta file on windows pc I didn't get any meterpreter shell.

Tested on Windows 10 v1809 (updated)

**Comment by r00t-3xp10it** [comment]
some builds are beeing flaged by **amsi** now ..
in a few days i will add new payloads with av evasion technics to venom project..

mean while try the 'shellter' module **(option 18**)..
![pic](http://i63.tinypic.com/2nh2khv.png)

**Comment by usama7628674** [comment]
@usama7628674 Also I think .hta files don't work in newer version of windows 10 v1809.

**Comment by etrnlnetshadow** [comment]
For some reason module 18 is sending me back to choose agent number 
![module](https://user-images.githubusercontent.com/39320689/62595005-367ec080-b8a2-11e9-9ee2-b389f2249e9d.png)

**Comment by r00t-3xp10it** [comment]
question: do you have `zenity` packet installed @etrnlnetshadow ???
because that error seems that your distro does not have the packet installed..
