### ISSUE TITLE
ERREUR

### ISSUE THREAD

**Issue by kel12345678** [r00t-3xp10it/venom#33]
hello i think i have an error during the installation because when i leave the script i have :
[☠] Exit Console -> Stoping Services...
./venom.sh: 10746: ./venom.sh: /etc/init.d/metasploit: not found
[☠] Report-Bugs: https://github.com/r00t-3xp10it/venom/issues
please help me

**Comment by kel12345678** [comment]
and how uninstall this script and dependances?

**Comment by r00t-3xp10it** [comment]
the error in line **10746** its because your distro does not start metasploit service with that command.
the script un-installation its easy, just delete the correspondent folder, now the dependencies installed by this tool will remain behind (they need to be manually un-installed)

**Comment by kel12345678** [comment]
OK I understand better then I have to start the service manually. how to add a self installation when the target will download the payload via apache2 on his iPhone and or Android (setoolkit media generator) can you steer me if you have a better idea? and my last question is that venom can compromise an iPhone 6?.Thank you for you job it 's very good!

**Comment by r00t-3xp10it** [comment]
1º 'I have to start the service manually' <-- start and stop ..
2º 'self installation' <-- i dont know how to do that on android or ios..
3º 'iphone6' <-- i dont know, because i dont have one to test it, but i belive it will work ..

**Comment by kel12345678** [comment]
ok thanks ;)
