### ISSUE TITLE
{resize, zenity} command not found

### ISSUE THREAD

**Issue by RenJunFeng** [r00t-3xp10it/venom#35]
./setup.sh: line 8: resize: command not found
./setup.sh: line 47: zenity: command not found

**Comment by r00t-3xp10it** [comment]
resize https://www.mankier.com/1/resize (not important)
zenity: https://help.gnome.org/users/zenity/ (zenity its importante)

Just install **zenity** package and everything will work fine ..

**Comment by Anonymous8650** [comment]
try to update python

**Comment by r00t-3xp10it** [comment]
./setup.sh: <--- `its one BASH error -on a bash script named setup.sh`
line 8:  <--- `on line nº 8`

resize: command not found <--- `resize its a shell command that allow me to set prompt size
(thats not an importante bug that stops script execution)`

zenity: command not found <-- `zenity allows me to use GUI's in sh scripts`
(this is IMPORTANTE, and must be installed to use 90% of bash my tools)
