### ISSUE TITLE
Windows Agent Number 18 aborting module execution.

### ISSUE THREAD

**Issue by etrnlnetshadow** [r00t-3xp10it/venom#37]
When I select Agent number 18 it aborts and sends me back to the select menu. Thanks in advance! Awesome tool.
![module](https://user-images.githubusercontent.com/39320689/62595092-8198d380-b8a2-11e9-9b11-0fe1782e1a1d.png)

**Comment by etrnlnetshadow** [comment]
This is in fact happening with whichever agent I choose actually I am using parrot OS @ Linux parrot 5.1.0-parrot1-3t-amd64 #1 SMP Parrot 5.1.3-1parrot1.3t (2019-05-20) x86_64 GNU/Linux

**Comment by ThePirat91** [comment]
Hello, I have the problems as you even after two years.
Was you able to solve them?

Thanks
