### ISSUE TITLE
生成exe报错，安装依赖报错

### ISSUE THREAD

**Issue by Gumihx** [r00t-3xp10it/venom#40]
As soon as I run the generated windows exe, it shows that it has stopped working. How to solve the problem is that Kali 2019.4 can't install venom. When installing its relevant environment, it directly reports an error。

**Comment by r00t-3xp10it** [comment]
this report will not help me identify the problem ...
1) what categorie did you have chosen ?
2) what agent nº as giving the error
3) what kind of error ??
