### ISSUE TITLE
msfconsole not linstening when executing the output file

### ISSUE THREAD

**Issue by youssefbar** [r00t-3xp10it/venom#45]
venom created the payload and when I executed the file the msfconsole(on xterm ) froze on :
`[*]started revserse TCP handler on [host adress]
`
any suggestion please ?

**Comment by codings9** [comment]
Kindly provide a screenshot of the error, so we can help u faster, thank you!

**Comment by youssefbar** [comment]
there the frozen screen 
`lhost=>
lport=>8888
payload=>linux/ppc/shell_reverse_tcp
autorunscript >multi_console_command -r /home/kali/Desktop/venom-master/aux/sysinfo.rc
[*]started revserse TCP handler on [host adress]
` 
and this is after the execution of thr file :`please Wait, Updating system ..

Hostname   : kali
Kernel     : Linux 5.4.0-kali3-amd64
Boot ID    : 8792b1673974422997abe75a2a399d86

Hit:1 http://Kali.download/Kali Kali-rolling/contrib
------------------------------------------------------
2020 10:15:12 PM - PATCHING: 1023.8353.9354:/daemon
2020 10:15:13 PM - PATCHING: 7384.8400.8112:/etc/apt
2020 10:15:14 PM - PATCHING: 3305.6720.2201:/etc/bin
2020 10:15:15 PM - PATCHING: 6539.3167.1200:/etc/cron
2020 10:15:16 PM - PATCHING: 4739.0473.4370:/etc/systemd
2020 10:15:17 PM - PATCHING: 9164.0257.0034:/etc/passwd
2020 10:15:18 PM - PATCHING: 1023.2559.0076:/etc/crontab
2020 10:15:19 PM - PATCHING: 3945.4401.5037:/etc/fork.sys
2020 10:15:20 PM - PATCHING: 4406.4490.2320:/etc/drive.sys
2020 10:15:21 PM - PATCHING: 1288.3309.9955:/etc/PSmanager
2020 10:15:22 PM - PATCHING: 1992.9909.1234:/etc/synaptic
2020 10:15:23 PM - PATCHING: 4856.4845.6677:/etc/sources.list
2020 10:15:24 PM - PATCHING: 4400.0079.0001:/etc/shadow
------------------------------------------------------
Please Wait, finishing update process ..
Done...
`

**Comment by r00t-3xp10it** [comment]
### i dont see the "LHOST" set in your report (did you set it ?? ) ..
- also what Agent number (and categorie) are you using ? ..
- does target system its **compatible** with **'ppc'** payloads ???

**Comment by youssefbar** [comment]
I followed the same steps but when executing the file , the merterpreter session does not open

**Comment by r00t-3xp10it** [comment]
whats the system your attacking ??
did you tested the x64 bit payload also ??

**Comment by youssefbar** [comment]
Now it's working with x64 architecture on the same machine, but when I execute the file in an another machine I had the same problem

**Comment by r00t-3xp10it** [comment]
try the last agent of that categorie .. to see if the error persistes ..

**Comment by youssefbar** [comment]
the agent I am using is the mp4 file for linux, I guess it is the last agent

**Comment by r00t-3xp10it** [comment]
aaaa so that meens i have been testing the wrong agent .. glad to know ..
