### ISSUE TITLE
I cant do installation 

### ISSUE THREAD

**Issue by Hassoor** [r00t-3xp10it/venom#49]
Hi when i try to install venom I entered 
cd venom-main
But it doesnt work. it showed " bash: cd: venom-main: No such file or directory "
any help here 
Thank you

**Comment by Hassoor** [comment]
In addition :

ARNING: Unable to locate package i686-w64-mingw32-gcc
    To solve this issue make sure you have the right repositories in sources.list
    With the right repositories in sources.list, you need to run apt-get update
    and then run the installation command for the mingw-w64 package again.
    KALI: https://docs.kali.org/general-use/kali-linux-sources-list-repositories

**Comment by luizamag** [comment]
Hm... did you tried: 
cd Desktop
git clone [file link]

**Comment by codings9** [comment]
> Hi when i try to install venom I entered
> cd venom-main
> But it doesnt work. it showed " bash: cd: venom-main: No such file or directory "
> any help here
> Thank you

Try this:
https://youtu.be/djJ9aIGESRE

**Comment by codings9** [comment]
> In addition :
> 
> ARNING: Unable to locate package i686-w64-mingw32-gcc
> To solve this issue make sure you have the right repositories in sources.list
> With the right repositories in sources.list, you need to run apt-get update
> and then run the installation command for the mingw-w64 package again.
> KALI: https://docs.kali.org/general-use/kali-linux-sources-list-repositories

Try this:
https://youtu.be/djJ9aIGESRE
