### ISSUE TITLE
getting timeout errors

### ISSUE THREAD

**Issue by ouli0826** [r00t-3xp10it/venom#53]

**Comment by ouli0826** [comment]
Error running command screenshot: Rex::TImeoutError Operation timed out. and cannot take any screen shots

**Comment by codings9** [comment]
Please send a screenshot of the attacking machine and if possible the target, guessing your target might look like: 
![F48222CF-BAAA-4D25-93E8-7DB1A448CF5C](https://user-images.githubusercontent.com/6113072/79628806-30abd100-80f9-11ea-8399-6d31bbbcf2a7.jpeg), hence the error.

We need more info or screenshots....😷

**Comment by r00t-3xp10it** [comment]
`Rex::TImeoutError` <-- This is a `RUBY` error (metasploit) ..
so this bug must be reported to metasploit team and not venom (bash) ..
