### ISSUE TITLE
Return to Main Menu

### ISSUE THREAD

**Issue by User1324-dot** [r00t-3xp10it/venom#54]
I can't start a payload.
**./venom.sh: 7637: xterm: not found**

**Comment by arash987** [comment]
me too i cant start a payload

**Comment by arash987** [comment]
i think the new version has a littel bugs!!!/  
guys can you help me?

**Comment by r00t-3xp10it** [comment]
Instaructions how to install XTERM -- https://github.com/r00t-3xp10it/venom/issues/34
