### ISSUE TITLE
Script execution aborted

### ISSUE THREAD

**Issue by Maguwar** [r00t-3xp10it/venom#56]
Its not installing the dependices and saying execution aborted.
If anyone knows how to solve it so please help me.

**Comment by r00t-3xp10it** [comment]
- [x] I belive your distro does not havethe **[zenity](https://help.gnome.org/users/zenity/)** package installed
- [x] This question have been allready fixed in **[this](https://github.com/r00t-3xp10it/venom/issues/35)** issue (report):
