### ISSUE TITLE
Rescrape function gone 

### ISSUE THREAD

**Issue by Toweliechaos** [r00t-3xp10it/venom#60]
This happened a while back and was fixed but has gone again. Once an item has scanned sources, there's no option to rescan again. This is in library items, not sure if present everywhere in the addon.

Thanks

**Comment by r00t-3xp10it** [comment]
I did not understand the problem ..please elaborate ..

**Comment by Toweliechaos** [comment]
OK. I have TV shows in my kodi library that scrape venom. If you 'play' an episode, it will scan for sources. Once it has done this scan, it will not scan again. There used to be an option to 'rescrape item' but this has disappeared.

I hope this is clear? Let me know if not.

**Comment by r00t-3xp10it** [comment]
why dont you show me the video ???

**Comment by Toweliechaos** [comment]
I've taken a video but can't seem to add it to this thread. Let me know of a way to get it to you.

**Comment by Toweliechaos** [comment]
https://youtu.be/u_lOywbwgH4

**Comment by r00t-3xp10it** [comment]
iam in work rigth now ..
but i will watch it as soon a arrive home ..thanks..

**Comment by Toweliechaos** [comment]
Huh?

**Comment by r00t-3xp10it** [comment]
this is the venom i develop ...
https://www.youtube.com/watch?v=r_t2DPbDgME

**Comment by Toweliechaos** [comment]
Ha, sorry. Someone pointed me to you for the other venom!
