### ISSUE TITLE
Listener not starting on Amsi Evasion Payload Number 1

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [r00t-3xp10it/venom#63]
Hi!

I am using that File Less Payload in Amsi-Evasion Module, The payload gets delivered successfully and I start the .ps1 script with the PowerShell On target computer, It executes successfully but on the kali side it shows Press Any Key to start Handler, I press key and the Handler doesnt starts only, How can i start the listener manually? For The ps1 script?

**Comment by r00t-3xp10it** [comment]
- 1º- i need a **`screenshot`** to see the error ..
- 2º - do you have **`netcat`** installed on attacker machine ???
because amsi evasion agents nº 1, 2, 3 requires netcat listenner ...

#### Manual start netcat listenner
`sudo nc -lvp <port number>`

**Comment by VySec-Secure** [comment]
So do i need to install netcat on target machine? Because I already have netcat installed on kali linux

**Comment by r00t-3xp10it** [comment]
netcat its only needed in **attacker** machine (listenner)
something its wrong with your netcat install ..

Execute the follow commands to check if nc its working fine
`sudo nc -lvp <port number>`

`xterm -T "netcat" -e "sudo nc -lvp <port number>"`

**Comment by VySec-Secure** [comment]
Ok and as you told that you need to install xterm for chars.raw, so will pip install xterm work?

**Comment by r00t-3xp10it** [comment]
pip its for **PYTHON** ...
apt-get install xterm <-- its the command we need to install xterm ..

## thats why your listenner does not start,, because it requires **xterm* console to spawn **netcat** ..
[netcat oficial webpage](https://invisible-island.net/xterm/)

**Comment by VySec-Secure** [comment]
Ok, And on the Windows machine do I haveto start the netcat listener? or the.ps1 file will start it when ran

**Comment by VySec-Secure** [comment]
Hi
I am trying the Windows Os Payloads in that I am trying number 20.
I run this attack and all i see is this console window. Even Windows Defender detected it.

![Capture](https://user-images.githubusercontent.com/67494275/86699115-85daed00-c02d-11ea-8660-95342a8bbc66.PNG)

**Comment by VySec-Secure** [comment]
HI
File Less stager works now, But what can i do from netcat? Can i execute system commands? Or open Notepad?

**Comment by r00t-3xp10it** [comment]
https://github.com/r00t-3xp10it/venom/issues/63#issuecomment-654572534 <-- thats the reason why i have written **`amsi evasion sub-menu`** because those technics are beeing detected now ..

https://github.com/r00t-3xp10it/venom/issues/63#issuecomment-654573792 <-- netcat gives you access to a console prompt were you can use since cmd commands to powershell commands (the sky its the limit if you are familiarized with thos languages) ... in other words: netcat allow you to interact with everything on remote host programatecly  ..

**Comment by VySec-Secure** [comment]
So can i execute any command or something? Or may be upload files or download them? And can you give tips on manually making these files more Undetectable?

**Comment by r00t-3xp10it** [comment]
you can not upload/download files only by using netcat ..
but we can use **`netcat`** to spawn for example **`ftp`** service that allow us to upload/download ..

Obfuscation: https://github.com/r00t-3xp10it/hacking-material-books/blob/master/obfuscation/simple_obfuscation.md

**Comment by VySec-Secure** [comment]
Alright!
I just have one question now, How can I execute commands while I have the connection on Netcat?

**Comment by VySec-Secure** [comment]
HI
I had a question that in Python, We can do process migration? Because I have made my own backdoor in python and now i want that it should run under a parent process such as explorer.exe

**Comment by r00t-3xp10it** [comment]
- 1º - netcat allow you to use almost all languages availabe (intalled) on target machine ...
      that means we have access to cmd, powershell, etc.. or interact with applications/services/etc ...
      `netstat -ano` <-- use native appl netstat to display a list of tcp/udp connections 
      `cmd.exe /c reg add 'hkcu/software/microsoft/startup /t reg_dword /d 1 /f` <-- use cmd.exe to add registry key

- 2º - migration can be done using any language ... 
        but i dont use very oven python so iam not the rigth perso to respond to that question ..

**Comment by Vedant-Bhalgama** [comment]
Hi!
I was thinking that how can we convert our python backdoor to .ps1? Or a macro file? To XML?
