### ISSUE TITLE
can't make make_avet.c & sh_format.c

### ISSUE THREAD

**Issue by ricko2991** [r00t-3xp10it/venom#68]
Hi, i'm problem in the avet instalation, i use option number 17 in windows-os payloads. when i run the  payload give me error in avet installation:
gcc: error: make_avet.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: sh_format.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.

**Comment by r00t-3xp10it** [comment]
dont run AVET ..its beeing detected this days ..
i have left those old payloads in venom to serve as a library of technics used ..
----
But i have recently updated venom project with **`AMSI evasion`** <-- this are the payloads that evades detection this days ..
