### ISSUE TITLE
not show the URL http://192.168.1.100/Download.html

### ISSUE THREAD

**Issue by ricko2991** [r00t-3xp10it/venom#72]
Hi, i want to open the url and give me alert in web browser:
"""""
Not Found
The requested URL was not found on this server.

Apache/2.4.46 (Debian) Server at 192.168.1.100 Port 80

""""""

This is my settings on AMSI BYPASS:
[i] AMSI MODULE SETTINGS
---
    LPORT    : 666                                                                                                                                                    
    LHOST    : 192.168.1.100                                                                                                                                         
    LOLBin   : WinHttpRequest                                                                                                                                         
    DROPPER  : /root/Toolswork/Bypass/venom/output/Update-KB1234.ps1                                                                                                  
    AGENT    : /root/Toolswork/Bypass/venom/output/Security-Update.ps1                                                                                                
    UPLOADTO : Fileless (trigger:tmp)                                                                                                                                 
    SILENT EXECUTION : OFF

**Comment by r00t-3xp10it** [comment]
question:
- 1º - Did you Install **`venom`** using **`setup.sh`** script ?
  - **`setup.sh`** will install dependencies AND config venom.sh **`settings`** file
  - **`venom.sh`** will use the **`settings`** file to config modules
- 2º - Do you have Apache2 installed on attacker machine ?
  - Its Apache2 webroot located at: **`/var/www/html`** ?

**HINT: Screenshots of the bugs are required for me to see whats appenning..**

**Comment by ricko2991** [comment]
1º - Did you Install venom using venom/aux/setup.sh script ?
ANSWER: Yes i install it properly, and not problem.
![Screenshot (7)](https://user-images.githubusercontent.com/67855001/91121471-6f1a5380-e6ca-11ea-9233-9d0a43819467.png)

2º - Do you have Apache2 installed on attacker machine?
       ANSWER: Yes
    - Its Apache2 webroot located at: /var/www/html ?
       ANSWER: Yes, it may have been set automatically in setup.sh and there were no problems with the configuration

3º - Is 192.168.1.100 the attacker ip address ??
       ANSWER: yes, its my ip address

4º - What shell does your system uses: bash or ZSH ?
       ANSWER: Bash


***But still not work. I open the link and not found the server

**Comment by r00t-3xp10it** [comment]
try to start apache2 manually ..can you ??

**Comment by ricko2991** [comment]
Yes, it works properly, when i installed setup.sh i chooce use venom domain name. Maybe this is why the link not show. Thanks a lot. 

Can i use ngrok in AMSI BYPASS options?

**Comment by r00t-3xp10it** [comment]
- 1º - so the problem was **`venom domain name`** config rigth ??
(its interfering with AMSI Evasion Payloads) <= after you reverted the setting it starts working ?

- 2º - nop ... because they required **`the files stored on apache2`** <= ngrok will not give remote access to apache2 ..

**Comment by ricko2991** [comment]
What the agent exactly can i use?

**Comment by r00t-3xp10it** [comment]
AGENT: In this case (agent nº5) its one .exe file
![fd](https://user-images.githubusercontent.com/23490060/91124870-2fd30f00-e698-11ea-9d0a-e70e7b1ae99b.png)

can you responde to 1º question ?? i need to know to make the proper changes to setup.sh

**Comment by ricko2991** [comment]
So when i'm not in the same network i can connect use my ip address? Not the ngrok address?

I run ngrok http 80 to expose the web service. I have not try it because i dont have windows device with different ip network

**Comment by r00t-3xp10it** [comment]
if you are not on same network ..
you can manually deliver **agent** with ngrok and recive the connection ..

**Comment by ricko2991** [comment]
Thanks A lot for helping me fix the problem. I have been trying soon. I Hope if i face the problem again i can fix it
