### ISSUE TITLE
SSL pem Fail

### ISSUE THREAD

**Issue by Akmaling** [r00t-3xp10it/venom#86]
<img width="321" alt="Untitled" src="https://user-images.githubusercontent.com/70948552/104916204-06da5000-5992-11eb-848b-613d28f1262b.png">
Please what could be the problem for the fail to clone ssl cert.  Thanks

**Comment by r00t-3xp10it** [comment]
https://github.com/r00t-3xp10it/venom/issues/77

**Comment by Akmaling** [comment]
> Issue: #77

@r00t-3xp10it  ..how you doing, it is not duplicate, I moved to new server and fresh install venom and ever since ssl cloning is no more working. Just wondering if I'm doing something wrong.  Thanks

**Comment by r00t-3xp10it** [comment]
Try to manually build the certificates:

```
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/C=US/ST=Michigan/L=Boston/O=Global Security/OU=IT Department/CN=microsoft.com"
```

**Comment by Akmaling** [comment]
Thanks
